### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by saud978** [mageplaza/magento-2-turkish-language-pack#1]
When try to install using composer I get this error 
==============
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mageplaza/magento-2-turkish-language-pack could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by samnguyen80** [comment]
Hi,

Sorry, we missed this message.
We have fixed this issue.
